@register(outgoing=True, pattern='^.introjay(?: |$)(.*)') 
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("Jay")
    sleep(1)
    await typew.edit("baik")
    sleep(1)
    await typew.edit("Tidak Sombong")
    sleep(1)
    await typew.edit("Ganteng")
    sleep(1)
    await typew.edit("Sopan")
    sleep(1)
    await typew.edit("Rajin")
    sleep(1)
    await typew.edit("Budiman")
    sleep(1)
    await typew.edit("Alim")
    sleep(1)
    await typew.edit("Berguna")
    sleep(1)
    await typew.edit("**Pekerja Keras Juga**")
    sleep(1)
    await typew.edit("Pemaaf")
    sleep(1)
    await typew.edit("Jujur")
    sleep(1)
    await typew.edit("Tidk Sombong")
    sleep(1)
    await typew.edit("Kaya")
    sleep(1)
    await typew.edit("Pokoknya Jay d best Dah")
    sleep(1)
    await typew.edit("Tidak Seperti Yang Lain")
    sleep(1)
    await typew.edit("Bersama Babi Membangun Negri")
    sleep(1)
    await typew.edit("eh salah salah, \nBersama **Jay dan Araa** Membangun Negri")
    
